### ISSUE TITLE
Andu Tutoveanu setup

### ISSUE THREAD

**Issue by adrianmaciuc** [adrianmaciuc/break-it-playwright-javascript-project#2]
Setup development tools 

- [x] VS Code
- [x] Node JS
- [x] Playwright
- [x] GIT
- [x] GITHUB account - [ AnduTutoveanu09 ](https://github.com/AnduTutoveanu09)
- [x] Link git with github
- [x] Associate github user to project

**Comment by AnduTutoveanu09** [comment]
Setup is complete
