### ISSUE TITLE
Levi Simon setup

### ISSUE THREAD

**Issue by adrianmaciuc** [adrianmaciuc/break-it-playwright-javascript-project#4]
Setup development tools 

- [x] VS Code
- [x] Node JS
- [x] Playwright
- [x] GIT
- [x] GITHUB account https://github.com/simonleventeattila
- [x] Link git with github
- [x] Associate github user to project

**Comment by adrianmaciuc** [comment]
We will check tomorrow if everything is correctly set up.

**Comment by simonleventeattila** [comment]
Sure thing! 
Please feel free to use my actions as an example (even if a bad one).
